os:
  - linux
  - osx

dist: trusty
sudo: required
language: ruby

env:
  global:
    - PATH="$PATH:/usr/local/Homebrew/bin:/home/linuxbrew/.linuxbrew/bin/"

addons:
  homebrew:
    update: true

install:
  - rvm use 2.3 --install --binary

before_script:
  - make

script:
  - make install
