stages:
  - osx
  - linux

jobs:
  include:
    - stage: osx
      name: Mac OS X
      os: osx
      sudo: required
      addons:
        homebrew:
          update: true
      before_script:
        - make
      script:
        - make install
    - stage: linux
      name: Linux
      os: linux
      language: ruby
      rvm:
        - 2.4.1
      before_script:
        - make
      script:
        - make install
