stages:
  - osx
  - linux

jobs:
  include:
    - stage: osx
      os: osx
      sudo: required
      addons:
        homebrew:
          update: true
      before_script:
        - make
      script:
        - make install
    - stage: linux
      os: linux
      services:
        - docker
      script:
        - docker build . -f test/Linux.Dockerfile --tag "dotfile:linux"
