stages:
  - mac
  - linux

jobs:
  include:
    - stage: mac
      name: Mac OS X
      os: osx
      sudo: required
      addons:
        homebrew:
          update: true
      before_script:
        - make
      script:
        - make install
    - stage: linux
      name: Linux
      os: linux
      language: ruby
      rvm:
        - 2.4.1
      before_script:
        - export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
        - echo "Removing existing ssh cofig" && rm "$HOME/.ssh/config" || true
      script:
        - make
        - make install
