os:
  - linux
  - osx

dist: xenial
sudo: required
language: ruby

env:
  global:
    - PATH="$PATH:/usr/local/Homebrew/bin:/home/linuxbrew/.linuxbrew/bin/"

addons:
  homebrew:
    update: true

before_script:
  - make

script:
  - make install
