#!/usr/bin/env bash

#/ Usage: generate [task]
#/ Run a given task within the script
#/
#/ TASKS:
#/      vscode, code      : Generate Visual Studio Code Extension
#/

set -e
source ./scripts/helper

# help()
function help () {
    grep ^#/ <"$0"| cut -c4-
    exit 2
}

# generate_vscode_extensions()
function generate_vscode_extensions () {
    code --list-extensions > "template/vscode/extensions.txt"
    c.success "Created Visual Studio Code Extensions List"
}

# main()
function main() {
    local task=$1

    case "$task" in
        "vscode" | "code")
            generate_vscode_extensions
        ;;
        *) help ;;
    esac
}

# --help
test "$1" = "--help" && {
    help
}

# Entrypoint
main $@
