#!/usr/bin/env bash

set -e
source ./scripts/helper

DOTFILE_INSTALL_DIR="$HOME/.dotfile"

function check_dotfile () {
    if [ -d "$DOTFILE_INSTALL_DIR" ]; then
        update_repo
    else 
        clone_repo
    fi
}

function clone_repo () {
    c.log "Downloading dotfile..."
    git clone git@github.com:socheatsok78/.dotfile.git "$DOTFILE_INSTALL_DIR"
}

function update_repo () {
    cd "$DOTFILE_INSTALL_DIR"
    git pull --rebase --stat origin master
}

function install_dotfile () {
    c.log "Installing dotfile..."
    cd "$DOTFILE_INSTALL_DIR"
    make && make install
}


function main () {
    check_dotfile
}

# Entrypoint
main;
