#!/usr/bin/env bash

# \033 or \e as an Escape character starts the escape sequence, 
# which in this case contains the controls to change colors.

# https://www.shellhacks.com/bash-colors/
# https://misc.flogisoft.com/bash/tip_colors_and_formatting

source ./zsh/.zsh_env
export LOCAL_BIN="$HOME/.local/bin"

# ========================================
# helper
# ========================================
function get_os () {
    uname -s
}

function make_local_bin () {
    mkdir -p "$LOCAL_BIN"
}

function brew_install_bundle () {
    if [ -f "Brewfile" ]; then
        c.info "Installing Brew Packages via Brewfile..."
        if [ -n "$CI" ]; then
            brew bundle --verbose # Install Brew Packages via Brewfile
        else
            brew bundle # Install Brew Packages via Brewfile
        fi
        
        c.success "Brew Packages is installed!"
    else
        c.error "Brewfile not found!"
    fi
}

# ========================================
# Logger
# ========================================
function c.log() {
    echo -e ">>> $@"
}

function c.line() {
    echo -e "\033[92m>>> $@\033[0m"
}

function c.warn() {
    echo -e "\033[33m>>> $@\033[0m"
}

function c.info() {
    echo -e "\033[94m>>> $@\033[0m"
}

function c.success() {
    echo -e "\033[92m>>> $@\033[0m"
}

function c.danger() {
    echo -e "\033[1;31m>>> $@\033[0m"
}

function c.error () {
    c.danger "$@"
}
