#!/usr/bin/env bash

# \033 or \e as an Escape character starts the escape sequence,
# which in this case contains the controls to change colors.

# https://www.shellhacks.com/bash-colors/
# https://misc.flogisoft.com/bash/tip_colors_and_formatting

source ./zsh/.zsh_env
export LOCAL_BIN="$HOME/.local/bin"

reset="\033[0m"
yellow="\033[33m"
blue="\033[94m"
green="\033[92m"
red="\033[1;31m"

# ========================================
# helper
# ========================================
function get_os () {
    uname -s
}

function make_local_bin () {
    mkdir -p "$LOCAL_BIN"
}

# ========================================
# Homebrew
# ========================================
function brew_install_bundle () {
    if [ -f "Brewfile" ]; then
        log_install "Brew Packages via Brewfile..."
        if [ -n "$CI" ]; then
            # Install Brew Packages via Brewfile
            brew bundle \
                --no-lock \
                --verbose
        else
            # Install Brew Packages via Brewfile
            brew bundle \
                --no-lock
        fi

        c.success "Brew Packages is installed!"
    else
        c.error "Brewfile not found!"
    fi
}

# ========================================
# Logger
# ========================================
function c.log() {
    echo -e ">>> $@"
}

function c.line() {
    echo -e "${green}>>> $@ ${reset}"
}

function c.warn() {
    echo -e "${yellow}>>> $@ ${reset}"
}

function c.info() {
    echo -e "${blue}>>> $@ ${reset}"
}

function c.success() {
    echo -e "${green}>>> $@ ${reset}"
}

function c.danger() {
    echo -e "${red}>>> $@ ${reset}"
}

function c.error () {
    c.danger "$@"
}

function log_install () {
    echo -e ">>> ${blue}[INSTALL]${reset}: $@"
}

function log_uninstall () {
    echo -e ">>> ${yellow}[UNINSTALL]${reset}: $@"
}

function log_install_success () {
    echo -e "${green}[SUCCESS]${reset}: $@"
}
