#!/bin/sh

#/
#/ Usage: dockrctl [OPTIONS] COMMAND
#/
#/ A self-sufficient runtime for containers
#/

test "$1" = "--help" && {
    grep ^#/ <"$0"| cut -c4-
    exit 2
}

test "$1" = "clean" && {
    case "$2" in
        "containers"|"ps")
            if [ -n "$(docker ps -aq)" ]; then
                docker stop $(docker ps -aq) || true
                docker rm $(docker ps -aq)
            fi
        ;;
        "images")
            if [ -n "$(docker images -aq)" ]; then
                docker rmi -f $(docker images -aq)
            fi
        ;;
        *)
            dockrctl --help
        ;;
    esac
    exit 0
}

docker "$@"
